name: NoNetheriteExpanded
version: 1.2.0
main: com.example.nonetheriteexpanded.NoNetheriteExpanded
api-version: '1.21'
description: Configure how you want netherite to be managed.
authors:
  - SushiMC
website: https://github.com/codingsushi79/nonetheriteplus
